const courses = [
  {
    title: "Office Automation",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    title: "CIT",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    title: "DIT",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    title: "Search Engine Optimization (SEO)",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    title: "Introduction to Web Development",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    title: "Front-End Development",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    title: "Back-End Development",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    title: "Wordpress Development",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    title: "Graphic Designing",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
];
