const courseData = [
  {
    id: "oap",
    title: "Office Automation and Productivity Tools",
    desc: "Boost your office efficiency with this course on office automation and productivity tools. Learn to streamline everyday tasks, manage data effectively, and use popular office software to its fullest potential. Whether you're a professional looking to optimize your workflow or a beginner wanting to gain essential office skills, this course has you covered.",
    fee: 1200,
    skills: [
      "Office Automation",
      "Microsoft Word",
      "Excel for Data Management",
      "Effective PowerPoint Presentations",
      "Efficient Email Management",
      "Organizing with Microsoft Outlook",
      "Collaboration and Cloud Storage",
      "Automation and Workflow Optimization",
    ],
    duration: 8,
    mode: "On-Site",
    timing: ["Tue", "Thu"],
    topics: [
      "Introduction to Office Automation",
      "Mastering Microsoft Word",
      "Excel for Data Management",
      "Effective PowerPoint Presentations",
      "Efficient Email Management",
      "Organizing with Microsoft Outlook",
      "Collaboration and Cloud Storage",
      "Automation and Workflow Optimization",
    ],
    syllabus: {
      "Week 1: Introduction to Office Automation": {
        "Understanding Office Automation": "https://example.com",
        "Benefits of Office Automation": "https://example.com",
        "Overview of Productivity Tools": "https://example.com",
        "Introduction to Microsoft Office Suite": "https://example.com",
      },
      "Week 2: Mastering Microsoft Word": {
        "Word Processing Basics": "https://example.com",
        "Creating and Formatting Documents": "https://example.com",
        "Working with Tables and Graphics": "https://example.com",
        "Document Collaboration and Review": "https://example.com",
      },
      "Week 3: Excel for Data Management": {
        "Spreadsheet Essentials": "https://example.com",
        "Data Entry and Formatting": "https://example.com",
        "Formulas and Functions": "https://example.com",
        "Charts and Graphs": "https://example.com",
        "Data Analysis and Visualization": "https://example.com",
      },
      "Week 4: Effective PowerPoint Presentations": {
        "Creating Dynamic Slides": "https://example.com",
        "Slide Transitions and Animation": "https://example.com",
        "Presentation Tips and Design": "https://example.com",
        "Delivering Impactful Presentations": "https://example.com",
      },
      "Week 5: Efficient Email Management": {
        "Managing Email Accounts": "https://example.com",
        "Organizing and Filtering Emails": "https://example.com",
        "Using Email Templates": "https://example.com",
        "Email Etiquette and Productivity": "https://example.com",
      },
      "Week 6: Organizing with Microsoft Outlook": {
        "Calendar and Task Management": "https://example.com",
        "Contacts and Address Books": "https://example.com",
        "Email Scheduling and Reminders": "https://example.com",
        "Outlook for Time Management": "https://example.com",
      },
      "Week 7: Collaboration and Cloud Storage": {
        "Cloud-Based Tools (Google Workspace, Microsoft 365)":
          "https://example.com",
        "Online Document Collaboration": "https://example.com",
        "File Sharing and Syncing": "https://example.com",
        "Security and Privacy Considerations": "https://example.com",
      },
      "Week 8: Automation and Workflow Optimization": {
        "Macros and Automation in Office Tools": "https://example.com",
        "Customizing Workflows": "https://example.com",
        "Troubleshooting and Support": "https://example.com",
        "Creating a Personalized Office Automation Plan": "https://example.com",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "cit",
    title: "Computer Information Technology (CIT)",
    desc: "Dive into the world of Computer Information Technology (CIT) in this comprehensive course. Learn the fundamentals of hardware, software, networking, and cybersecurity. Acquire the skills to troubleshoot computer issues, manage networks, and protect systems from cyber threats.",
    fee: 2200,
    skills: [
      "Computer Hardware and Operating Systems",
      "Networking Fundamentals",
      "Cybersecurity Basics",
      "Network Administration",
      "Cybersecurity and Data Protection",
    ],
    duration: 14,
    mode: "On-Site",
    timing: ["Tue", "Thu"],
    topics: [
      "Introduction to CIT",
      "Computer Hardware and Operating Systems",
      "Networking Fundamentals",
      "Cybersecurity Basics",
      "Network Administration",
      "Cybersecurity and Data Protection",
    ],
    syllabus: {
      "Week 1: Introduction to CIT": {
        "Understanding Computer Information Technology": "https://example.com",
        "The Role of CIT in Modern Businesses": "https://example.com",
        "Overview of Hardware and Software": "https://example.com",
        "CIT Ethics and Security": "https://example.com",
      },
      "Week 2-4: Computer Hardware and Operating Systems": {
        "Computer Components and Peripherals": "https://example.com",
        "CPU, RAM, and Storage Devices": "https://example.com",
        "Operating System Fundamentals": "https://example.com",
        "Installation and Configuration": "https://example.com",
      },
      "Week 5-7: Networking Fundamentals": {
        "Introduction to Networking": "https://example.com",
        "Networking Devices (Routers, Switches)": "https://example.com",
        "IP Addressing and Subnetting": "https://example.com",
        "Network Protocols (TCP/IP, DNS)": "https://example.com",
      },
      "Week 8-9: Cybersecurity Basics": {
        "Common Cybersecurity Threats": "https://example.com",
        "Security Best Practices": "https://example.com",
        "Password Management": "https://example.com",
        "Antivirus and Firewall Software": "https://example.com",
      },
      "Week 10-12: Network Administration": {
        "Network Design and Topologies": "https://example.com",
        "Configuring Routers and Switches": "https://example.com",
        "Wireless Networking": "https://example.com",
        "Troubleshooting Network Issues": "https://example.com",
      },
      "Week 13-14: Cybersecurity and Data Protection": {
        "Advanced Cybersecurity Measures": "https://example.com",
        "Data Encryption and Privacy": "https://example.com",
        "Incident Response and Recovery": "https://example.com",
        "CIT Career Paths and Certifications": "https://example.com",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "dit",
    title: "Diploma in Information Technology (DIT)",
    desc: "Earn a diploma in Information Technology (IT) with this comprehensive program. Cover a wide range of IT topics, from programming and database management to network administration and cybersecurity. Whether you're new to IT or aiming to enhance your skills, this diploma program will prepare you for a rewarding career in the tech industry.",
    fee: 3500,
    skills: [
      "IT Fundamentals",
      "Web Development and Design",
      "Database Management",
      "Networking Basics",
      "Programming and Software Development",
      "Network Administration",
      "Cybersecurity",
      "Capstone Project and Career Preparation",
    ],
    duration: 24,
    mode: "On-Site",
    timing: ["Mon", "Wed", "Fri"],
    topics: ["Year 1: Foundations of IT", "Year 2: Advanced IT Skills"],
    syllabus: {
      "Year 1: Foundations of IT": {
        "Semester 1: IT Fundamentals": {
          "Introduction to Information Technology": "https://example.com",
          "Basics of Computer Hardware and Software": "https://example.com",
          "Operating Systems and File Management": "https://example.com",
          "Introduction to Programming (Python)": "https://example.com",
        },
        "Semester 2: Web Development and Design": {
          "HTML5 and CSS3 for Web Development": "https://example.com",
          "JavaScript and Client-Side Scripting": "https://example.com",
          "Web Design Principles": "https://example.com",
          "Building Responsive Web Pages": "https://example.com",
        },
        "Semester 3: Database Management": {
          "Introduction to Databases and SQL": "https://example.com",
          "Relational Database Design": "https://example.com",
          "Database Implementation (MySQL)": "https://example.com",
          "Data Security and Privacy": "https://example.com",
        },
        "Semester 4: Networking Basics": {
          "Introduction to Networking Concepts": "https://example.com",
          "Network Protocols and Communication": "https://example.com",
          "Network Configuration and Troubleshooting": "https://example.com",
          "Introduction to Cybersecurity": "https://example.com",
        },
      },
      "Year 2: Advanced IT Skills": {
        "Semester 5: Programming and Software Development": {
          "Advanced Programming (Java, C#, or similar)": "https://example.com",
          "Software Development Lifecycle": "https://example.com",
          "Version Control Systems (e.g., Git)": "https://example.com",
          "Object-Oriented Programming (OOP)": "https://example.com",
        },
        "Semester 6: Network Administration": {
          "Network Security and Administration": "https://example.com",
          "Routing and Switching": "https://example.com",
          "Wireless Networking": "https://example.com",
          "Virtualization and Cloud Computing": "https://example.com",
        },
        "Semester 7: Cybersecurity": {
          "Cyber Threats and Vulnerabilities": "https://example.com",
          "Ethical Hacking and Penetration Testing": "https://example.com",
          "Security Policies and Compliance": "https://example.com",
          "Incident Response and Forensics": "https://example.com",
        },
        "Semester 8: Capstone Project and Career Preparation": {
          "Capstone Project in IT": "https://example.com",
          "Presentation and Documentation": "https://example.com",
          "Career Development and Job Search": "https://example.com",
          "IT Certifications and Professional Growth": "https://example.com",
        },
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "seo",
    title: "Search Engine Optimization (SEO)",
    desc: "Explore the art and science of SEO in this comprehensive course. Learn how to optimize websites for search engines, boost organic traffic, and improve search engine rankings. Whether you're new to SEO or want to sharpen your skills, this course will help you master the techniques and strategies.",
    fee: 1500,
    skills: [
      "Keyword Research and Analysis",
      "On-Page SEO",
      "Off-Page SEO and Link Building",
      "Technical SEO",
      "SEO Analytics and Tools",
      "SEO for Content and E-commerce",
      "SEO Strategy and Future Trends",
    ],
    duration: 10,
    mode: "On-Site",
    timing: ["Mon", "Wed", "Fri"],
    topics: [
      "Introduction to SEO",
      "Keyword Research and Analysis",
      "On-Page SEO",
      "Off-Page SEO and Link Building",
      "Technical SEO",
      "SEO Analytics and Tools",
      "SEO for Content and E-commerce",
      "SEO Strategy and Future Trends",
    ],
    syllabus: {
      "Week 1: Introduction to SEO": {
        "What is SEO and Why It Matters": "https://example.com",
        "Role of SEO in Digital Marketing": "https://example.com",
        "Search Engine Algorithms and Ranking Factors": "https://example.com",
        "Setting SEO Goals and Objectives": "https://example.com",
      },
      "Week 2: Keyword Research and Analysis": {
        "Importance of Keywords in SEO": "https://example.com",
        "Keyword Research Tools and Techniques": "https://example.com",
        "Long-tail Keywords and Search Intent": "https://example.com",
        "Competitor Analysis for Keywords": "https://example.com",
      },
      "Week 3-4: On-Page SEO": {
        "Optimizing Website Content for Keywords": "https://example.com",
        "Meta Tags and Descriptions": "https://example.com",
        "URL Structure and Internal Linking": "https://example.com",
        "Image Optimization and Alt Text": "https://example.com",
        "Mobile-Friendly and Responsive Design": "https://example.com",
      },
      "Week 5-6: Off-Page SEO and Link Building": {
        "Backlinks and Their Impact on Rankings": "https://example.com",
        "Strategies for Quality Link Building": "https://example.com",
        "Guest Posting and Outreach": "https://example.com",
        "Local SEO and Google My Business": "https://example.com",
      },
      "Week 7: Technical SEO": {
        "Website Speed and Performance": "https://example.com",
        "XML Sitemaps and Robots.txt": "https://example.com",
        "Schema Markup for Rich Snippets": "https://example.com",
        "Handling Duplicate Content Issues": "https://example.com",
      },
      "Week 8: SEO Analytics and Tools": {
        "Google Analytics for SEO": "https://example.com",
        "Google Search Console": "https://example.com",
        "SEO Tools for Performance Tracking": "https://example.com",
        "Reporting and Data Analysis": "https://example.com",
      },
      "Week 9: SEO for Content and E-commerce": {
        "Blog and Content Optimization": "https://example.com",
        "E-commerce SEO Best Practices": "https://example.com",
        "Product Page Optimization": "https://example.com",
        "User-generated Content and Reviews": "https://example.com",
      },
      "Week 10: SEO Strategy and Future Trends": {
        "Developing an SEO Strategy": "https://example.com",
        "Voice Search and Mobile SEO": "https://example.com",
        "SEO for Emerging Technologies (AI, IoT)": "https://example.com",
        "Preparing for Future SEO Challenges": "https://example.com",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "wdf",
    title: "Web Development Fundamentals",
    desc: "Unlock the world of web development in this comprehensive course. Learn HTML, CSS, JavaScript, and more to build modern, responsive websites. Whether you're a beginner or want to enhance your skills, this course offers hands-on training to create your web projects.",
    fee: 2000,
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "Responsive Design",
      "Git and GitHub",
      "Web Hosting",
      "Domain Management",
    ],
    duration: 12,
    mode: "On-Site",
    timing: ["Sat", "Sun"],
    topics: [
      "Introduction to Web Development",
      "HTML Fundamentals",
      "CSS Fundamentals",
      "Responsive Web Design",
      "JavaScript Basics",
      "Document Object Model (DOM)",
      "Web Design Principles",
      "Web Development Tools and Version Control",
      "Web Hosting and Deployment",
      "Web Development Project",
      "Final Project Presentations",
      "Recap and Next Steps",
    ],
    syllabus: {
      "Week 1: Introduction to Web Development": {
        "Overview of the Web Development Landscape": "https://iamark.tech",
        "Role of Web Developers": "https://iamark.tech",
        "Basics of Front-end and Back-end Development": "https://iamark.tech",
      },
      "Week 2: HTML Fundamentals": {
        "Introduction to HTML5": "https://iamark.tech",
        "Creating Web Pages with HTML": "https://iamark.tech",
        "Document Structure and Semantic Elements": "https://iamark.tech",
        "HTML Forms and Input Elements": "https://iamark.tech",
      },
      "Week 3: CSS Fundamentals": {
        "Introduction to CSS3": "https://iamark.tech",
        "Styling HTML Elements with CSS": "https://iamark.tech",
        "CSS Selectors and Properties": "https://iamark.tech",
        "CSS Layout and Positioning": "https://iamark.tech",
      },
      "Week 4: Responsive Web Design": {
        "Understanding Responsive Design": "https://iamark.tech",
        "CSS Media Queries": "https://iamark.tech",
        "Mobile-First Design Approach": "https://iamark.tech",
        "Testing and Debugging for Different Screen Sizes":
          "https://iamark.tech",
      },
      "Week 5: JavaScript Basics": {
        "Introduction to JavaScript": "https://iamark.tech",
        "Variables, Data Types, and Operators": "https://iamark.tech",
        "Control Structures (if statements, loops)": "https://iamark.tech",
        "Functions and Event Handling": "https://iamark.tech",
      },
      "Week 6: Document Object Model (DOM)": {
        "What is the DOM?": "https://iamark.tech",
        "Accessing and Modifying DOM Elements": "https://iamark.tech",
        "Event Handling with JavaScript": "https://iamark.tech",
        "Dynamic Web Page Manipulation": "https://iamark.tech",
      },
      "Week 7: Web Design Principles": {
        "Color Theory and Typography": "https://iamark.tech",
        "Layout Design and User Experience (UX)": "https://iamark.tech",
        "User Interface (UI) Design Best Practices": "https://iamark.tech",
        "Introduction to Wireframing and Mockups": "https://iamark.tech",
      },
      "Week 8: Web Development Tools and Version Control": {
        "Overview of Web Development Tools (e.g., text editors, code editors)":
          "https://iamark.tech",
        "Introduction to Version Control with Git": "https://iamark.tech",
        "Using GitHub for Collaboration and Version Control":
          "https://iamark.tech",
      },
      "Week 9: Web Hosting and Deployment": {
        "Web Hosting Options": "https://iamark.tech",
        "Domain Registration": "https://iamark.tech",
        "Deploying a Website to a Hosting Server": "https://iamark.tech",
        "Basic Server Management": "https://iamark.tech",
      },
      "Week 10: Web Development Project": {
        "Final Project Overview": "https://iamark.tech",
        "Brainstorming and Planning": "https://iamark.tech",
        "Development and Testing": "https://iamark.tech",
        "Presentation and Review": "https://iamark.tech",
      },
      "Week 11: Final Project Presentations": {
        "Each student presents their web development project to the class.":
          "https://iamark.tech",
        "Peer feedback and evaluation.": "https://iamark.tech",
      },
      "Week 12: Recap and Next Steps": {
        "Review of Course Topics": "https://iamark.tech",
        "Discussion of Further Learning Paths (e.g., Back-end Development, Frameworks)":
          "https://iamark.tech",
        "Career Opportunities in Web Development": "https://iamark.tech",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "fwd",
    title: "Front-end Web Development",
    desc: "Explore the exciting world of front-end web development in this comprehensive course. Learn essential technologies and skills needed to create engaging and user-friendly websites. From HTML and CSS to JavaScript and responsive design, this course equips you with the tools to build modern web interfaces.",
    fee: 2200,
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "Responsive Design",
      "Git and GitHub",
      "Web Hosting",
      "Web Accessibility",
    ],
    duration: 10,
    mode: "On-Site",
    timing: ["Mon", "Wed"],
    topics: [
      "Introduction to Front-end Development",
      "HTML Fundamentals",
      "CSS Fundamentals",
      "Responsive Web Design",
      "JavaScript Basics",
      "Document Object Model (DOM)",
      "Web Design Best Practices",
      "Version Control with Git and GitHub",
      "Web Hosting and Deployment",
      "Final Project and Portfolio",
    ],
    syllabus: {
      "Week 1: Introduction to Front-end Development": {
        "Understanding the Front-end Development Landscape":
          "https://example.com",
        "Role of Front-end Developers": "https://example.com",
        "Basics of HTML, CSS, and JavaScript": "https://example.com",
      },
      "Week 2: HTML Fundamentals": {
        "Introduction to HTML5": "https://example.com",
        "Creating Well-Structured Web Pages": "https://example.com",
        "Semantic HTML Elements": "https://example.com",
        "HTML Forms and Input Validation": "https://example.com",
      },
      "Week 3: CSS Fundamentals": {
        "Introduction to CSS3": "https://example.com",
        "Styling Web Pages with CSS": "https://example.com",
        "CSS Layout Techniques (Flexbox and Grid)": "https://example.com",
        "CSS Transitions and Animations": "https://example.com",
      },
      "Week 4: Responsive Web Design": {
        "Principles of Responsive Design": "https://example.com",
        "CSS Media Queries": "https://example.com",
        "Mobile-First Development": "https://example.com",
        "Testing and Debugging for Multiple Devices": "https://example.com",
      },
      "Week 5: JavaScript Basics": {
        "Introduction to JavaScript": "https://example.com",
        "Variables, Data Types, and Operators": "https://example.com",
        "Control Structures (if statements, loops)": "https://example.com",
        "Functions and Event Handling": "https://example.com",
      },
      "Week 6: Document Object Model (DOM)": {
        "Working with the DOM": "https://example.com",
        "Modifying HTML and CSS with JavaScript": "https://example.com",
        "Event Handling and Event Delegation": "https://example.com",
        "Creating Interactive Web Pages": "https://example.com",
      },
      "Week 7: Web Design Best Practices": {
        "Typography and Color Theory": "https://example.com",
        "User Experience (UX) and User Interface (UI) Design":
          "https://example.com",
        "Web Accessibility Guidelines": "https://example.com",
        "Design Tools and Resources": "https://example.com",
      },
      "Week 8: Version Control with Git and GitHub": {
        "Introduction to Version Control": "https://example.com",
        "Setting Up Git and GitHub": "https://example.com",
        "Creating and Managing Repositories": "https://example.com",
        "Collaborative Workflows with Git": "https://example.com",
      },
      "Week 9: Web Hosting and Deployment": {
        "Web Hosting Options": "https://example.com",
        "Domain Registration and Management": "https://example.com",
        "Deploying Websites to a Web Server": "https://example.com",
        "Server Configuration and Maintenance": "https://example.com",
      },
      "Week 10: Final Project and Portfolio": {
        "Applying Skills to a Real-world Project": "https://example.com",
        "Portfolio Development": "https://example.com",
        "Presenting and Showcasing Your Work": "https://example.com",
        "Future Learning Paths and Career Opportunities": "https://example.com",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "bed",
    title: "Back-end Web Development",
    desc: "Dive into the world of back-end web development in this comprehensive course. Learn the fundamentals of server-side programming, databases, and web application development. Gain the skills to create robust, secure, and scalable web applications.",
    fee: 2500,
    skills: [
      "Server-side Programming",
      "Database Design",
      "RESTful API Development",
      "Authentication and Authorization",
      "Middleware Development",
      "Database Management (SQL and NoSQL)",
      "Deployment and Scalability",
    ],
    duration: 12,
    mode: "On-Site",
    timing: ["Tue", "Thu"],
    topics: [
      "Introduction to Back-end Development",
      "Server-side Programming Basics",
      "Databases and Data Modeling",
      "Building RESTful APIs",
      "Authentication and Authorization",
      "Middleware and Express.js",
      "Working with Databases (SQL)",
      "Working with Databases (NoSQL)",
      "REST API Authentication",
      "Testing and Debugging",
      "Deployment and Scalability",
      "Final Project and Deployment",
    ],
    syllabus: {
      "Week 1: Introduction to Back-end Development": {
        "Understanding Back-end Development Concepts": "https://example.com",
        "Role of Back-end Developers": "https://example.com",
        "Overview of Server-side vs. Client-side Development":
          "https://example.com",
      },
      "Week 2: Server-side Programming Basics": {
        "Introduction to Server-side Programming Languages":
          "https://example.com",
        "Setting Up a Development Environment": "https://example.com",
        "Handling HTTP Requests and Responses": "https://example.com",
        "Creating a Simple Server": "https://example.com",
      },
      "Week 3: Databases and Data Modeling": {
        "Introduction to Databases": "https://example.com",
        "Database Design and Normalization": "https://example.com",
        "Structured Query Language (SQL) Basics": "https://example.com",
        "CRUD Operations (Create, Read, Update, Delete)": "https://example.com",
      },
      "Week 4: Building RESTful APIs": {
        "What is a RESTful API?": "https://example.com",
        "Designing API Endpoints": "https://example.com",
        "Implementing API Routes": "https://example.com",
        "Handling Data Validation and Error Responses": "https://example.com",
      },
      "Week 5: Authentication and Authorization": {
        "User Authentication Methods": "https://example.com",
        "Implementing User Registration and Login": "https://example.com",
        "Role-Based Access Control": "https://example.com",
        "Securing API Endpoints": "https://example.com",
      },
      "Week 6: Middleware and Express.js": {
        "Understanding Middleware": "https://example.com",
        "Using Express.js as a Server Framework": "https://example.com",
        "Creating Custom Middleware": "https://example.com",
        "Error Handling Middleware": "https://example.com",
      },
      "Week 7: Working with Databases (SQL)": {
        "Connecting to a Database": "https://example.com",
        "Querying Data from Databases": "https://example.com",
        "Managing Database Transactions": "https://example.com",
        "Database Security Best Practices": "https://example.com",
      },
      "Week 8: Working with Databases (NoSQL)": {
        "Introduction to NoSQL Databases": "https://example.com",
        "CRUD Operations with NoSQL Databases": "https://example.com",
        "Data Modeling in NoSQL": "https://example.com",
        "Mongoose (for MongoDB) or Similar Libraries": "https://example.com",
      },
      "Week 9: REST API Authentication": {
        "Token-Based Authentication": "https://example.com",
        "JSON Web Tokens (JWT)": "https://example.com",
        "Implementing Authentication in RESTful APIs": "https://example.com",
        "User Session Management": "https://example.com",
      },
      "Week 10: Testing and Debugging": {
        "Writing Unit Tests for Back-end Code": "https://example.com",
        "Integration Testing": "https://example.com",
        "Debugging Techniques for Back-end Applications": "https://example.com",
        "Test-Driven Development (TDD)": "https://example.com",
      },
      "Week 11: Deployment and Scalability": {
        "Deployment Options": "https://example.com",
        "Containerization (Docker)": "https://example.com",
        "Load Balancing and Scaling Strategies": "https://example.com",
        "Monitoring and Performance Optimization": "https://example.com",
      },
      "Week 12: Final Project and Deployment": {
        "Building a Full-fledged Web Application": "https://example.com",
        "Deploying the Application to a Hosting Server": "https://example.com",
        "Project Presentation and Review": "https://example.com",
        "Future Learning Paths and Career Opportunities": "https://example.com",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "fsd",
    title: "Full Stack Web Development",
    desc: "Embark on a journey to become a Full Stack Web Developer. This comprehensive course covers both front-end and back-end development, equipping you with the skills to create dynamic, responsive, and feature-rich web applications. Master HTML, CSS, JavaScript, server-side programming, databases, and more.",
    fee: 3000,
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "Front-end Frameworks (React, Vue.js, etc.)",
      "Node.js or Server-side Language (e.g., Python, Ruby)",
      "Building RESTful APIs",
      "Authentication and Authorization",
      "Database Management (SQL and NoSQL)",
      "ORM (Sequelize, Mongoose, etc.)",
      "Full Stack Integration",
      "State Management",
      "Testing and Debugging",
      "Real-time Web Applications",
      "Microservices Architecture",
      "Advanced Topics (e.g., Websockets, GraphQL)",
      "Deployment and Scaling Strategies",
      "Security Best Practices",
      "DevOps and Continuous Integration",
      "Career Development and Job Preparation",
    ],
    duration: 16,
    mode: "On-Site",
    timing: ["Mon", "Wed", "Fri"],
    topics: [
      "Introduction to Full Stack Development",
      "Front-end Development",
      "Back-end Development",
      "Full Stack Integration",
      "Final Project and Advanced Topics",
    ],
    syllabus: {
      "Week 1: Introduction to Full Stack Development": {
        "Understanding Full Stack Development": "https://example.com",
        "Roles and Responsibilities of Full Stack Developers":
          "https://example.com",
        "Overview of the Web Development Stack": "https://example.com",
      },
      "Week 2-4: Front-end Development": {
        "HTML5 and Semantic Markup": "https://example.com",
        "CSS3 Styling and Layout": "https://example.com",
        "JavaScript Fundamentals": "https://example.com",
        "Responsive Web Design": "https://example.com",
        "Front-end Frameworks (e.g., React, Vue.js)": "https://example.com",
      },
      "Week 5-8: Back-end Development": {
        "Server-side Programming (Node.js, Python, Ruby)":
          "https://example.com",
        "Building RESTful APIs": "https://example.com",
        "Authentication and Authorization": "https://example.com",
        "Middleware Development": "https://example.com",
        "Databases (SQL and NoSQL)": "https://example.com",
        "ORM (e.g., Sequelize, Mongoose)": "https://example.com",
        "Deployment and Server Management": "https://example.com",
      },
      "Week 9-12: Full Stack Integration": {
        "Connecting Front-end and Back-end": "https://example.com",
        "REST API Integration": "https://example.com",
        "State Management in Web Applications": "https://example.com",
        "Testing and Debugging Full Stack Apps": "https://example.com",
        "Building Real-time Web Applications": "https://example.com",
        "Microservices Architecture": "https://example.com",
      },
      "Week 13-16: Final Project and Advanced Topics": {
        "Full Stack Web Application Project": "https://example.com",
        "Advanced Topics (e.g., Websockets, GraphQL)": "https://example.com",
        "Deployment and Scaling Strategies": "https://example.com",
        "Security Best Practices": "https://example.com",
        "DevOps and Continuous Integration": "https://example.com",
        "Career Development and Job Preparation": "https://example.com",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "wpd",
    title: "WordPress Development",
    desc: "Master the art of WordPress development in this comprehensive course. Learn to build custom themes, plugins, and extend the functionality of WordPress to create powerful websites. Whether you're a beginner or an experienced developer, this course will take your WordPress skills to the next level.",
    fee: 1800,
    skills: [
      "WordPress CMS",
      "Theme Development",
      "Plugin Development",
      "Custom Post Types and Taxonomies",
      "Custom Fields and Meta Boxes",
      "Security and Performance Optimization",
      "Deployment and Maintenance",
    ],
    duration: 8,
    mode: "On-Site",
    timing: ["Tue", "Thu"],
    topics: [
      "Introduction to WordPress",
      "Theme Development",
      "Plugin Development",
      "Advanced WordPress Functionality",
      "Security and Performance Optimization",
      "WordPress Deployment and Maintenance",
    ],
    syllabus: {
      "Week 1: Introduction to WordPress": {
        "Understanding WordPress as a Content Management System (CMS)":
          "https://example.com",
        "WordPress vs. Traditional Web Development": "https://example.com",
        "Setting Up a Local WordPress Development Environment":
          "https://example.com",
        "Tour of the WordPress Dashboard": "https://example.com",
      },
      "Week 2-3: Theme Development": {
        "Introduction to WordPress Themes": "https://example.com",
        "Theme Development Best Practices": "https://example.com",
        "Creating a Custom Theme from Scratch": "https://example.com",
        "Styling WordPress Themes with CSS": "https://example.com",
      },
      "Week 4-5: Plugin Development": {
        "Introduction to WordPress Plugins": "https://example.com",
        "Plugin Development Basics": "https://example.com",
        "Creating Custom Plugins": "https://example.com",
        "Interacting with WordPress Core Functions": "https://example.com",
      },
      "Week 6: Advanced WordPress Functionality": {
        "Custom Post Types and Taxonomies": "https://example.com",
        "Custom Fields and Meta Boxes": "https://example.com",
        "Building Custom Widgets": "https://example.com",
        "Implementing Custom Shortcodes": "https://example.com",
      },
      "Week 7: Security and Performance Optimization": {
        "WordPress Security Best Practices": "https://example.com",
        "Performance Optimization Techniques": "https://example.com",
        "Caching and Content Delivery Networks (CDNs)": "https://example.com",
        "Backup and Disaster Recovery": "https://example.com",
      },
      "Week 8: WordPress Deployment and Maintenance": {
        "Deploying WordPress Websites": "https://example.com",
        "Migrating WordPress Sites": "https://example.com",
        "Routine Maintenance and Updates": "https://example.com",
        "Troubleshooting Common WordPress Issues": "https://example.com",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "gd",
    title: "Graphic Designing",
    desc: "Unlock your creative potential in graphic design. This course covers design principles, industry-standard software, and hands-on projects to help you create stunning visuals for print and digital media. Whether you're a beginner or looking to enhance your design skills, this course will inspire your creativity.",
    fee: 2000,
    skills: [
      "Design Principles",
      "Adobe Creative Cloud (Photoshop, Illustrator, InDesign)",
      "Vector Graphics",
      "Digital Imaging",
      "Typography and Layout Design",
      "Web and Social Media Design",
      "Print Design and Branding",
      "Motion Graphics and Animation",
      "Portfolio Development",
      "Career Opportunities",
    ],
    duration: 12,
    mode: "On-Site",
    timing: ["Mon", "Wed", "Fri"],
    topics: [
      "Introduction to Graphic Design",
      "Design Software and Tools",
      "Digital Design for Web and Social Media",
      "Print Design and Branding",
      "Motion Graphics and Animation",
      "Portfolio Development and Future Opportunities",
    ],
    syllabus: {
      "Week 1: Introduction to Graphic Design": {
        "Understanding Graphic Design as Visual Communication":
          "https://example.com",
        "Role of Graphic Designers": "https://example.com",
        "Overview of Design Software and Tools": "https://example.com",
        "Fundamentals of Design Principles": "https://example.com",
      },
      "Week 2-4: Design Software and Tools": {
        "Adobe Creative Cloud Suite (Photoshop, Illustrator, InDesign)":
          "https://example.com",
        "Introduction to Vector Graphics": "https://example.com",
        "Digital Imaging and Photo Manipulation": "https://example.com",
        "Typography and Layout Design": "https://example.com",
      },
      "Week 5-7: Digital Design for Web and Social Media": {
        "Designing Graphics for Websites": "https://example.com",
        "Social Media Graphics and Branding": "https://example.com",
        "Creating Engaging Infographics": "https://example.com",
        "Designing for User Experience (UX)": "https://example.com",
      },
      "Week 8-10: Print Design and Branding": {
        "Print Design Essentials (Brochures, Flyers, Business Cards)":
          "https://example.com",
        "Corporate Branding and Logo Design": "https://example.com",
        "Packaging Design": "https://example.com",
        "Preparing Print-Ready Files": "https://example.com",
      },
      "Week 11: Motion Graphics and Animation": {
        "Introduction to Animation": "https://example.com",
        "Creating Animated Graphics and GIFs": "https://example.com",
        "Video Editing Basics": "https://example.com",
        "Exporting Graphics for Multimedia": "https://example.com",
      },
      "Week 12: Portfolio Development and Future Opportunities": {
        "Building a Graphic Design Portfolio": "https://example.com",
        "Presenting and Showcasing Your Work": "https://example.com",
        "Career Paths in Graphic Design": "https://example.com",
        "Freelancing and Professional Growth": "https://example.com",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
];
