const courseData = [
  {
    id: "oa",
    title: "Office Automation",
    desc: "Understand the basics of Computers & Microsoft Office",
    fee: 2000,
    skills: ["MS Office"],
    duration: 10,
    mode: "On-Site",
    timing: ["Sat", "Sun"],
    topics: [
      "Windows",
      "Microsoft Word",
      "Microsoft Excel",
      "Microsoft Powerpoint",
    ],
    syllabus: {
      "Heading 1": {
        "Sub-Topic 1": "https://iamark.tech",
        "Sub-Topic 2": "https://iamark.tech",
        "Sub-Topic 3": "https://iamark.tech",
      },
      "Heading 2": {
        "Sub-Topic 1": "https://iamark.tech",
        "Sub-Topic 2": "https://iamark.tech",
        "Sub-Topic 3": "https://iamark.tech",
      },
    },
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "cit",
    title: "CIT",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "dit",
    title: "DIT",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "seo",
    title: "Search Engine Optimization (SEO)",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "iwb",
    title: "Introduction to Web Development",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "fed",
    title: "Front-End Development",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "bed",
    title: "Back-End Development",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "wd",
    title: "Wordpress Development",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
  {
    id: "gd",
    title: "Graphic Designing",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio, ex.",
    skills: [],
    duration: 10,
    imgUrl: "https://placehold.co/240x190",
    detailPage: "",
  },
];
